theme: jekyll-theme-minimal
title: Aaryan Fredrick's portfolio
description: Hi! I'm Aaryan, a Mechanical Engineering undergraduate student at the University of Toronto with an interest in design and manufacturing, as well as a strong focus on leadership.
